sudo: required
services:
  - docker

before_install:
  - docker build -t abraralam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abraralam/docker-react npm run test -- --watchAll=false