sudo: required
services:
  - docker

before_install:
  - docker build -t abraralam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abraralam/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_react_new"
  env: "Dockerreactnew-env"
  bucket_name: "elasticbeanstalk-us-east-2-906027485223"
  bucket_path: "docker_react_new"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  

